name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang
    steps:
      - uses: actions/checkout@v4
      - run: go build
      - uses: golangci/golangci-lint-action@v3
      - run: go test -covermode atomic -coverprofile coverage.txt
      - uses: codecov/codecov-action@v4
      - run: go test -bench .
